### ISSUE TITLE
Installation failed on Ubuntu 22.04

### ISSUE THREAD

**Issue by MrBPAE** [btey/openproject-gitlab-integration#18]
# Installation 

* Fresh installed `openproject` as package [link](https://www.openproject.org/docs/installation-and-operations/installation/packaged/#ubuntu-2204)
* created the `Gemfile.custom` and copied it to `/etc/openproject/Gemfile.custom`
* `sudo chown openproject:openproject /etc/openproject/Gemfile.custom`
* `sudo openproject config:set CUSTOM_PLUGIN_GEMFILE=/etc/openproject/Gemfile.custom` [link](https://www.openproject.org/docs/installation-and-operations/configuration/plugins/)
* `sudo openproject configure` ==> **fail**

Whatever I try from there end in a unsolvable error. 

How is it possible to install the gitlab integration?

# Error

```log 
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

If this is a development machine, remove the /opt/openproject/Gemfile freeze 
by running `bundle config unset frozen`.

The list of sources changed
The dependencies in your gemfile changed

You have added to the Gemfile:
* openproject-gitlab-integration
```

# Gemfile.custom 

```log 
cat /etc/openproject/Gemfile.custom
group :opf_plugins do
  gem 'openproject-gitlab-integration', git: 'https://github.com/btey/openproject-gitlab-integration.git', :branch => 'master'
end
```

# Environment 

```log 
openproject/unknown,now 12.2.0-1660563236.b31b7e8b.jammy amd64 [installed]
```
```log 
ruby --version
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
```

```log 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by btey** [comment]
Hi @MrBPAE 

I have been able to reproduce this error with the latest version of OpenProject 12.2.0. However, this particular bug I think is outside the scope of development for this plugin. It may be a regression of a previous OpenProject bug since with recent previous versions this error did not occur. Also, the gem is actually named "openproject-gitlab_integration", and the one you have defined is "openproject-gitlab-integration" (not to be confused with the name of the project on Github). If the installation had gotten to the point of validating the gem I think it would have given you an error. The error appears only because of adding a change to the Gemfile, not because of the plugin code.

However, it is also true that OpenProject 12.2.0 introduces some internal changes that make the plugin incompatible with the current 2.0.5 version. I have a fix ready to test in the "Fix_compatibilty_with_OpenProject_12.2.0" branch. But I can't test it properly with version 12.2.0 because there seems to be another problem related to redirecting to "https".

I have tried the installation with Docker, both direct (Dockerfile+Gemfile) and custom (download code, include the plugin and build docker image) and in all cases I get the same error "ssl_error_rx_record_too_long". I think it is related to this bug that they have open for the next patch version:

https://community.openproject.org/projects/openproject/work_packages/43759/activity?query_id=3466

I have also tried the manual installation, and it also redirects me to "https" when I don't have it defined so I can't test it. We will have to wait for the next version 12.2.1 to see if these bugs are solved.

Thanks for the patience,
Ben

**Comment by btey** [comment]
Hi @MrBPAE 

After the release of the v12.2.1 the "Fix_compatibilty_with_OpenProject_12.2.0" branch worked without errors building a docker image with the plugin. I'll be merging the fix into the main branch shortly. I add some screenshots.

![Screen Shot 2022-08-22 at 15 34 47](https://user-images.githubusercontent.com/14983519/186006431-ec287411-2305-4be0-a5d1-fa2067d892e6.png)

![Screen Shot 2022-08-22 at 15 35 58](https://user-images.githubusercontent.com/14983519/186006453-d9da1768-29bd-4a07-8245-454743bb3102.png)

![Screen Shot 2022-08-22 at 15 36 27](https://user-images.githubusercontent.com/14983519/186006486-2656f248-98de-47a3-b2e8-b14d731fb94f.png)

![Screen Shot 2022-08-22 at 15 36 52](https://user-images.githubusercontent.com/14983519/186006518-be745e9d-41c8-4e07-a69e-da477b949094.png)

When version 2.0.6 is ready try it when you get a chance with v12.2.1 and if you still have problems let me know.

Thanks,
Ben
