### ISSUE TITLE
Configure a repository in one project

### ISSUE THREAD

**Issue by wesleyguirra** [btey/openproject-gitlab-integration#2]
There's a way to configure a gitlab repository for specific projects?

**Comment by btey** [comment]
Hi Wes!

Not directly since the link is with the Work Package not with the Project itself. But what can be done is in the case of having several Gitlab repositories for different projects is to create a generic Gitlab user for each repository in OpenProject:

**Gitlab Repo 1**
**User in openProject:** Gitlab Bot 1 (or whatever you prefer)
**Project in OpenProject:** Project 1

**Gitlab Repo 2**
**User in OpenProject:** Gitlab Bot 2 (or whatever you prefer)
**Project in OpenProject:** Project 2

Then you can indicate that the **Gitlab Bot 1** user is a member only of project 1, and that can add comments.
You would do the same with the other user in the project 2.

This way, if by mistake in **Gitlab Repo 1** someone try to make a link to a work package that belongs to the Project 2, OpenProject's own security should deny it and simply no log would be created in the Work Package activity.

Basically it is to have instead of a single user "Gitlab Bot", to have different users for different repositories in Gitlab, and then associate them to the OpenProject projects that you need.

It's just an idea.

I take this opportunity to comment that I am finishing a new version based on the update that the OpenProject team has made in its Github plugin. Basically it will do the same of the new plugin except in the case of Gitlab Pipelines since there is a bug in Gitlab where the webhook is not including the ID of the Merge Request and then the process cannot associate the pipeline result with the MR registered in OpenProject. I have an open issue waiting for a response (https://gitlab.com/gitlab-org/gitlab/-/issues/345028). But here is a screenshot of what will be visible in the new Gitlab tab:

![Screenshot 2021-11-19 at 13 43 54](https://user-images.githubusercontent.com/14983519/142624744-b8182a51-4616-4b49-bb29-9f879eb41fa9.png)

Regards,
Ben

**Comment by wesleyguirra** [comment]
Amazing! I'm waiting for this new version. TY!!

LMK if you need some help.

**Comment by btey** [comment]
If you are interested today I published the version 2.0 (pre-release). It should work without errors, but for now please try it in a test environment.

Thanks!
