### ISSUE TITLE
Can't install the PlugIn

### ISSUE THREAD

**Issue by stefanHau** [btey/openproject-gitlab-integration#21]
Hi, if I run the installation for this PlugIn acording to your instructions, I get the following error:

![grafik](https://user-images.githubusercontent.com/108061106/186882071-403a8bfb-86dc-45fe-a4fe-66f445a9dda6.png)

I get the same error if I do the installation with the DEB/RPM integration guide.

Can you help me?

**Comment by ardisian** [comment]
I second this. I've tried modifying the Gemfiles and versions and the version in the openproject-gitlab_integration.gemspec file. As well, i've attempted a manual install of the plugin, but once running openproject configure and during it's postinstall script it still has issue's.

**Comment by btey** [comment]
Hi @ardisian 

The command "openproject configure" will not work in manual installations; as far as I know this executable is not included with the sources. This command is only for DEB/RPM installations. So maybe you mixed the installation methods and for sure will not work. I will try to open a ticket in OpenProject just in case they can confirm the problem with DEB/RPM because I get the same error with OpenProject 12.2.0 when I was testing the new major version.

If you can try using docker installation, it's one of the latest tested with the latest versions and it works fine.

Thanks,
Ben

**Comment by btey** [comment]
Hi @ardisian @stefanHau 

The new release of OpenProject 12.2.3 should work now with DEB/RPM installations. Tested locally and works.

Thanks,
Ben
