### ISSUE TITLE
Error 500 

### ISSUE THREAD

**Issue by anujecom** [btey/openproject-gitlab-integration#42]
I installed and configured this plugin, but not data receive in Open project also, 

when i tried to test this webhook. push & comment is Hook executed successfully: HTTP 200 but issue and merge  are given below  error. 

"Hook executed successfully but returned HTTP 500

[Home](https://project.emtpl.in/)
Search
You are here:
translation missing: en.label_webhooks/incoming/hook_plural
Content
[Error 500] An error occurred on the page you were trying to access. If you continue to experience problems please contact your Ayka Tech- Project administrator for assistance."

how can i Resolve this.

Regards
Ak

**Comment by nth-zik** [comment]
Same on me

**Comment by btey** [comment]
Hi @anujecom and @nth-zik 

If I understand correctly, the error you are receiving is from GitLab when you do the webhook test. Here you have to keep in mind that not all webhooks that can be tested will return HTTP 200. Some of them do not include the necessary information in the payload. Therefore, it does not mean that it does not work. If push & Comments works for you then it's fine. The important thing here is that GitLab sends and receives a response from OpenProject.

From here, if you can see the GitLab tab in OpenProject, it means that the plugin is installed and activated in the project. The next thing is to verify the permissions of the user defined as "gitlab bot" in OpenProject. Check the logs in case any message appears indicating that the user does not have permissions to write comments or similar in the project/task.

Regards,
Ben

**Comment by nth-zik** [comment]
<img width="1169" alt="image" src="https://github.com/btey/openproject-gitlab-integration/assets/22862747/55c3ae06-2523-4f92-9b2e-1708cb1adc55">
Hi, since we upgrade to 13.0.7. It's not work anymore
Here is the log

`<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en" class>
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width">
<title>Sign in | PM Project</title>
<meta name="app_base_path" content />
<base href="/" />
<meta name="boards_demo_data_available" content="true" />
<meta name="demo_view_of_type_team_planner_seeded" content="true" />
<meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="GsLY4/67KUNkyt3E7mbuIRAgmuUbdwC9dTI4EWiaxn39dV9cCRSEMi5prtJ4M/3uo/xDJ8ZsLbKronJsYl0tRg==" />
<meta name="openproject_initializer" data-locale="en" data-defaultLocale="en" data-firstWeekOfYear data-firstDayOfWeek data-environment="production" data-edition="standard" />

<link rel="apple-touch-icon" type="image/png" href="/assets/apple-touch-icon-120x120-7cc127b22515cb03208e0cd2ab29c30545d6c1d232a8d68058c751bf29626354.png" sizes="120x120" />
<script src="/assets/frontend/vendor.ebb29324890acea2.js"></script><script src="/assets/frontend/polyfills.500da43400d59e04.js"></script><script src="/assets/frontend/runtime.94788a8299b7255c.js"></script><script src="/assets/frontend/main.e34e96d0ceb8c126.js"></script><link rel="stylesheet" href="/assets/frontend/styles.c62f36ec3b2d0bf8.css" media="all" />
<link rel="stylesheet" href="/highlighting/styles/96daec2ac6a26a8f6399cbed54c907ef803ced35321ebf215d7a501c635b79d0.css" media="all" />
<style type="text/css">

    .op-logo--link {
      background-image: url(/custom_style/1697535735/logo/PM_Solution_white_143x40.png);
    }
  </style>
<style type="text/css">

  /* Overwrite Primer primitives */
  [data-color-mode] {
      --body-background: var(--color-canvas-default);
      --body-font-color: var(--color-fg-default);
      --color-accent-fg: var(--content-link-color) !important;

        --color-btn-primary-bg:  #349939 !important;
        --color-btn-primary-hover-bg:  #2b7d2f !important;
        --color-accent-fg: #275BB5 !important;
  }
</style>
<style type="text/css">
    :root {
        --primary-color: #3270DB;
        --primary-color--minor1: #709be6;
        --primary-color--minor2: #adc6f1;
        --primary-color--minor3: #d6e2f8;
        --primary-color--major1: #285aaf;
        --primary-color--major2: #1e4383;
        --primary-color--major3: #142d58;
        --primary-color-dark: #163473;
        --alternative-color: #349939;
        --button--alt-highlight-background-hover-color: #2b7d2f;
        --content-link-color: #275BB5;
        --header-bg-color: #05002C;
        --header-item-bg-hover-color: #163473;
        --header-item-font-color: #FFFFFF;
        --header-item-font-hover-color: #FFFFFF;
        --main-menu-bg-color: #0E2045;
        --main-menu-bg-selected-background: #3270DB;
        --main-menu-bg-hover-background: #163473;
        --main-menu-font-color: #FFFFFF;
        --main-menu-hover-font-color: #FFFFFF;
        --main-menu-selected-font-color: #FFFFFF;
        --main-menu-border-color: #EAEAEA;
        --main-menu-border-width: 1px;
    }

</style>
<link rel="icon" type="image/png" href="/custom_style/1697535735/favicon/PM_Solution_512x512.png" sizes="32x32">

<style type="text/css">
      #content .login-auth-providers a.auth-provider.auth-provider-google {
        background-image: url('/assets/openid_connect/auth_provider-google-ee1c9e37fdc6d74a3b2403785d442557d2600f9c255a1aa85abeb628f98ff83f.png');
      }
      .op-app-header #nav-login-content .login-auth-providers a.auth-provider.auth-provider-google {
        background-image:  url('/assets/openid_connect/auth_provider-google-ee1c9e37fdc6d74a3b2403785d442557d2600f9c255a1aa85abeb628f98ff83f.png') ;
      }
      .login-auth-providers a.auth-provider.auth-provider-google {
        background-image: url('/assets/openid_connect/auth_provider-google-ee1c9e37fdc6d74a3b2403785d442557d2600f9c255a1aa85abeb628f98ff83f.png') ;
      }
    </style>

<meta name="current_menu_item" content />
</head>
<body class="theme-core_design controller-account action-login ee-banners-hidden env-production bcf-deactivated __overflowing_element_container __overflowing_body" data-relative_url_root="/" data-overflowing-identifier=".__overflowing_body" data-rendered-at="2023-11-10T15:47:31Z" data-controller="application" data-color-mode="light" data-light-theme="light">
<div class="warning-bar--wrapper">
</div>
<noscript>
  <div class="top-shelf">
    <p>
      <span>
        <i class="icon3 icon-warning"  aria-hidden="true"></i>
        <strong>JavaScript disabled</strong>
      </span>
      You need to activate JavaScript in order to use OpenProject!
      <a href="http://www.enable-javascript.com/" target="_blank">Learn more</a>
    </p>
  </div>
</noscript>
<op-toasts-container></op-toasts-container>
<op-modal-overlay></op-modal-overlay>
<spot-drop-modal-portal></spot-drop-modal-portal>
<div id="wrapper" style class="can-hide-navigation nosidebar">
<header class="op-app-header">
<div class="op-app-header--start">
<h1 class="hidden-for-sighted">
Top Menu
</h1>
<main-menu-toggle></main-menu-toggle>
<a href class="hidden-for-sighted skip-navigation-link" id="skip-navigation--content" aria-label="Click here to skip over the menu and go to the content">
Jump to content
</a>
<ul class="op-app-menu op-app-menu_drop-left"></ul>
</div>
<div class="op-app-header--center">
<div class="op-logo"><a class="op-logo--link" href="https://project.pmsolution.tech/">Home</a></div>
</div>
<div class="op-app-header--end">
<div class="op-app-search">
<label class="hidden-for-sighted" for="q">Search</label>
<global-search-input></global-search-input>
</div>
<ul class="op-app-menu"><li class="op-app-menu--item op-app-menu--item_has-dropdown hidden-for-mobile"><a icon="icon-menu" title="Modules" aria-haspopup="true" class="op-app-menu--item-action  " span_class="op-app-menu--item-title " href="#"><i class="icon-menu" aria-hidden="true"></i><span class="op-app-menu--item-title "></span></a><ul style="display:none" id="more-menu" class="op-app-menu--dropdown op-menu drop-down--modules "><li class="main-menu-item" data-name="activity"><a class="activity-menu-item op-menu--item-action" title="Activity" data-qa-selector="op-menu--item-action" href="https://project.pmsolution.tech/activity"><span class="spot-icon spot-icon_1_25 spot-icon_checkmark"></span><span class="op-menu--item-title"><span class="ellipsis">Activity</span></span></a></li></ul></li><li class="op-app-menu--item op-app-menu--item_has-dropdown op-app-help hidden-for-mobile"><a title="Help" class="op-app-menu--item-action" aria-haspopup="true" href="#"><span class="spot-icon spot-icon_1_25 spot-icon_help op-app-help--icon"></span></a><ul style="display:none" class="op-app-menu--dropdown op-menu"><li class="op-menu--item"><span class="op-menu--headline" title="Getting started">Getting started</span></li><li class="op-menu--item" data-augmented-model-wrapper data-activation-selector=".onboarding-modal--activation-link" data-modal-iframe-url="https://player.vimeo.com/video/163426858?autoplay=1" data-modal-class-name="onboarding-modal">
<a title="Introduction video" class="op-menu--item-action onboarding-modal--activation-link" href>Introduction video</a>
<div class="modal-delivery-element">
<div class="spot-modal--header">
<span class="spot-icon spot-icon_user"></span>
<span>Welcome to PM Project</span>
</div>
<div class="spot-divider"></div>
<div class="onboarding--main spot-modal--body spot-container">
<div class="onboarding--video-block">
<div class="onboarding--video-text">
<span>Get a quick overview of project management and team collaboration with OpenProject. You can restart this video from the help menu.</span>
</div>
<div class="onboarding--video iframe-target-wrapper">
</div>
</div>
</div>
<div class="onboarding--footer spot-action-bar">
<div class="spot-action-bar--right">
<button class="button button_no-margin spot-action-bar--action spot-modal--cancel-button" dynamic-content-modal-close-button title="Close">Close</button>
</div>
</div>
</div>
</li>
<hr class="op-menu--separator"></hr><li class="op-menu--item"><span class="op-menu--headline" title="Help and suppor…`
`Date: Fri, 10 Nov 2023 15:47:31 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Vary: Accept,Accept-Encoding
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 875d5e34-d8c5-49c3-8dc3-710f2cfa5efd
X-Runtime: 0.140925
Strict-Transport-Security: max-age=63072000; includeSubDomains, max-age=31536000
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: origin-when-cross-origin
Content-Security-Policy: default-src 'self'; base-uri 'self'; connect-src 'self' https://start.openproject.com; font-src 'self' data:; form-action 'self'; frame-ancestors 'self'; frame-src 'self' https://player.vimeo.com https://releases.openproject.com/v1/check.svg; img-src * data: blob:; media-src 'self'; object-src https://releases.openproject.com/v1/check.svg; script-src 'self' 'nonce-4KbiP0UACeKdWIiAAcL3H59etRa81Ep6C+Kp5FtDfIc=' 'unsafe-inline'; style-src 'self' 'unsafe-inline'
Cf-Cache-Status: DYNAMIC
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=tXkSovvdtIbYadM55RF8LiXtm9c7glW159pa3Prc66aH6wk%2BSHrz6LDVb3qXBlqC9JMuQckzs%2FN%2FyvDByCJ10m1qO7apGg%2Ft6Mgc3CxeK0IIKXJ2Z2a89U6GSNBrdc59h3pJ0puzF7IPPw%3D%3D"}],"group":"cf-nel","max_age":604800}
Nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Server: cloudflare
Cf-Ray: 823f6f392cc1134d-ATL
Alt-Svc: h3=":443"; ma=86400`
`{
  "object_kind": "push",
  "event_name": "push",
  "before": "4b7a4fb7133c39c5ce0fc31d674c53372ff80b1a",
  "after": "7f3c4e88c8b4b14fd6248aff6091343b5c9ca8fc",
  "ref": "refs/heads/user-story/704-pm-apt-view-camera-screens-and-activity-log",
  "ref_protected": false,
  "checkout_sha": "7f3c4e88c8b4b14fd6248aff6091343b5c9ca8fc",
  "message": null,
  "user_id": 13348918,
  "user_name": "Hưng Nguyễn Tấn",
  "user_username": "pmhungnt",
  "user_email": null,
  "user_avatar": "https://secure.gravatar.com/avatar/28b3e6482a3e282139faabe7529b68da?s=80&d=identicon",
  "project_id": 46526950,
  "project": {
    "id": 46526950,
    "name": "PM Apartment",
    "description": "",
    "web_url": "https://gitlab.com/pmhungnt/pm-apartment",
    "avatar_url": "https://gitlab.com/uploads/-/system/project/avatar/46526950/pma.png",
    "git_ssh_url": "git@gitlab.com:pmhungnt/pm-apartment.git",
    "git_http_url": "https://gitlab.com/pmhungnt/pm-apartment.git",
    "namespace": "Hưng Nguyễn Tấn",
    "visibility_level": 0,
    "path_with_namespace": "pmhungnt/pm-apartment",
    "default_branch": "main",
    "ci_config_path": "",
    "homepage": "https://gitlab.com/pmhungnt/pm-apartment",
    "url": "git@gitlab.com:pmhungnt/pm-apartment.git",
    "ssh_url": "git@gitlab.com:pmhungnt/pm-apartment.git",
    "http_url": "https://gitlab.com/pmhungnt/pm-apartment.git"
  },
  "commits": [
    {
      "id": "7f3c4e88c8b4b14fd6248aff6091343b5c9ca8fc",
      "message": "Add rtsp player\n",
      "title": "Add rtsp player",
      "timestamp": "2023-11-10T22:47:09+07:00",
      "url": "https://gitlab.com/pmhungnt/pm-apartment/-/commit/7f3c4e88c8b4b14fd6248aff6091343b5c9ca8fc",
      "author": {
        "name": "Tan Hung",
        "email": "[REDACTED]"
      },
      "added": [
        "pma/external-module/react-native-vlc-media-player/.gitignore",
        "pma/external-module/react-native-vlc-media-player/LICENSE",
        "pma/external-module/react-native-vlc-media-player/README.md",
        "pma/external-module/react-native-vlc-media-player/VLCPlayer.js",
        "pma/external-module/react-native-vlc-media-player/android/build.gradle",
        "pma/external-module/react-native-vlc-media-player/android/proguard-rules.pro",
        "pma/external-module/react-native-vlc-media-player/android/src/main/AndroidManifest.xml",
        "pma/external-module/react-native-vlc-media-player/android/src/main/java/com/yuanzhou/vlc/ReactVlcPlayerPackage.java",
        "pma/external-module/react-native-vlc-media-player/android/src/main/java/com/yuanzhou/vlc/vlcplayer/ReactVlcPlayerView.java",
        "pma/external-module/react-native-vlc-media-player/android/src/main/java/com/yuanzhou/vlc/vlcplayer/ReactVlcPlayerViewManager.java",
        "pma/external-module/react-native-vlc-media-player/android/src/main/java/com/yuanzhou/vlc/vlcplayer/VideoEventEmitter.java",
        "pma/external-module/react-native-vlc-media-player/android/src/main/res/values/strings.xml",
        "pma/external-module/react-native-vlc-media-player/app.plugin.js",
        "pma/external-module/react-native-vlc-media-player/example/.bundle/config",
        "pma/external-module/react-native-vlc-media-player/example/.node-version",
        "pma/external-module/react-native-vlc-media-player/example/.watchmanconfig",
        "pma/external-module/react-native-vlc-media-player/example/Gemfile",
        "pma/external-module/react-native-vlc-media-player/example/android/app/build.gradle",
        "pma/external-module/react-native-vlc-media-player/example/android/app/debug.keystore",
        "pma/external-module/react-native-vlc-media-player/example/android/app/proguard-rules.pro",
        "pma/external-module/react-native-vlc-media-player/example/android/app/src/debug/AndroidManifest.xml",
        "pma/external-module/react-native-vlc-media-player/example/android/app/src/debug/java/com/vlcmediaplayerexample/ReactNativeFlipper.java",
        "pma/external-module/react-native-vlc-media-player/example/android/app/src/main/AndroidManifest.xml",
        "pma/external-module/react-native-vlc-media-player/example/android/app/src/main/java/com/vlcmediaplayerexample/MainActivity.java",
        "pma/external-module/react-native-vlc-media-player/example/android/app/src/main/java/com/vlcmediaplayerexample/MainApplication.java",
        "pma/external-module/react-native-vlc-media-player/example/android/app/src/main/res/drawable/rn_edit_text_material.xml",
        "pma/external-module/react-native-vlc-media-player/example/android/app/src/main/res/mipmap-hdpi/ic_launcher.png",
        "pma/external-module/react-native-vlc-media-player/example/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png",
        "pma/external-module/react-native-vlc-media-player/example/android/app/src/main/res/mipmap-mdpi/ic_launcher.png",
        "pma/external-module/react-native-vlc-media-player/example/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png",
        "pma/external-module/react-native-vlc-media-player/example/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png",
        "pma/external-module/react-native-vlc-media-player/example/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png",
        "pma/external-module/react-native-vlc-media-player/example/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png",
        "pma/external-module/react-native-vlc-media-player/example/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png",
        "pma/external-module/react-native-vlc-media-player/example/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png",
        "pma/external-module/react-native-vlc-media-player/example/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png",
        "pma/external-module/react-native-vlc-media-player/example/android/app/src/main/res/values/strings.xml",
        "pma/external-module/react-native-vlc-media-player/example/android/app/src/main/res/values/styles.xml",
        "pma/external-module/react-native-vlc-media-player/example/android/app/src/release/java/com/vlcmediaplayerexample/ReactNativeFlipper.java",
        "pma/external-module/react-native-vlc-media-player/example/android/build.gradle",
        "pma/external-module/react-native-vlc-media-player/example/android/gradle.properties",
        "pma/external-module/react-native-vlc-media-player/example/android/gradle/wrapper/gradle-wrapper.jar",
        "pma/external-module/react-native-vlc-media-player/example/android/gradle/wrapper/gradle-wrapper.properties",
        "pma/external-module/react-native-vlc-media-player/example/android/gradlew",
        "pma/external-module/react-native-vlc-media-player/example/android/gradlew.bat",
        "pma/external-module/react-native-vlc-media-player/example/android/settings.gradle",
        "pma/external-module/react-native-vlc-media-player/example/app.json",
        "pma/external-module/react-native-vlc-media-player/example/babel.config.js",
        "pma/external-module/react-native-vlc-media-player/example/index.js",
        "pma/external-module/react-native-vlc-media-player/example/ios/.xcode.env",
        "pma/external-module/react-native-vlc-media-player/example/ios/File.swift",
        "pma/external-module/react-native-vlc-media-player/example/ios/Podfile",
        "pma/external-module/react-native-vlc-media-player/example/ios/VlcMediaPlayerExample-Bridging-Header.h",
        "pma/external-module/react-native-vlc-media-player/example/ios/VlcMediaPlayerExample.xcodeproj/project.pbxproj",
        "pma/external-module/react-native-vlc-media-player/example/ios/VlcMediaPlayerExample.xcodeproj/xcshareddata/xcschemes/VlcMediaPlayerExample.xcscheme",
        "pma/external-module/react-native-vlc-media-player/example/ios/VlcMediaPlayerExample/AppDelegate.h",
        "pma/external-module/react-native-vlc-media-player/example/ios/VlcMediaPlayerExample/AppDelegate.mm",
        "pma/external-module/react-native-vlc-media-player/example/ios/VlcMediaPlayerExample/Images.xcassets/AppIcon.appiconset/Contents.json",
        "pma/external-module/react-native-vlc-media-player/example/ios/VlcMediaPlayerExample/Images.xcassets/Contents.json",
        "pma/external-module/react-native-vlc-media-player/example/ios/VlcMediaPlayerExample/Info.plist",
        "pma/external-module/react-native-vlc-media-player/example/ios/VlcMediaPlayerExample/LaunchScreen.storyboard",
        "pma/external-module/react-native-vlc-media-player/example/ios/VlcMediaPlayerExample/main.m",
        "pma/external-module/react-native-vlc-media-player/example/ios/VlcMediaPlayerExampleTests/Info.plist",
        "pma/external-module/react-native-vlc-media-player/example/ios/VlcMediaPlayerExampleTests/VlcMediaPlayerExampleTests.m",
        "pma/external-module/react-native-vlc-media-player/example/metro.config.js",
        "pma/external-module/react-native-vlc-media-player/example/package.json",
        "pma/external-module/react-native-vlc-media-player/example/react-native.config.js",
        "pma/external-module/react-native-vlc-media-player/example/src/App.tsx",
        "pma/external-module/react-native-vlc-media-player/expo/android/withGradleTasks.js",
        "pma/external-module/react-native-vlc-media-player/expo/ios/withMobileVlcKit.js",
        "pma/external-module/react-native-vlc-media-player/expo/withVlcMediaPlayer.js",
        "pma/external-module/react-native-vlc-media-player/index.js",
        "pma/external-module/react-native-vlc-media-player/ios/RCTVLCPlayer-Bridging-Header.h",
        "pma/external-module/react-native-vlc-media-player/ios/RCTVLCPlayer.swift",
        "pma/external-module/react-native-vlc-media-player/ios/RCTVLCPlayer.xcodeproj/project.pbxproj",
        "pma/external-module/react-native-vlc-media-player/ios/RCTVLCPlayer.xcodeproj/project.xcworkspace/contents.xcworkspacedata",
        "pma/external-module/react-native-vlc-media-player/ios/RCTVLCPlayerManager.m",
        "pma/external-module/react-native-vlc-media-player/ios/RCTVLCPlayerManager.swift",
        "pma/external-module/react-native-vlc-media-player/package-lock.json",
        "pma/external-module/react-native-vlc-media-player/package.json",
        "pma/external-module/react-native-vlc-media-player/playerView/BackHandle.js",
        "pma/external-module/react-native-vlc-media-player/playerView/ControlBtn.js",
        "pma/external-module/react-native-vlc-media-player/playerView/SizeController.js",
        "pma/external-module/react-native-vlc-media-player/playerView/TimeLimit.js",
        "pma/external-module/react-native-vlc-media-player/playerView/VLCPlayerView.js",
        "pma/external-module/react-native-vlc-media-player/playerView/index.js",
        "pma/external-module/react-native-vlc-media-player/react-native-vlc-media-player.podspec"
      ],
      "modified": [
        "pma/ios/Podfile.lock",
        "pma/ios/pma.xcodeproj/project.pbxproj",
        "pma/ios/pma.xcodeproj/xcshareddata/xcschemes/pma.xcscheme",
        "pma/ios/pma.xcodeproj/xcshareddata/xcschemes/pmaDev.xcscheme",
        "pma/ios/pma.xcodeproj/xcshareddata/xcschemes/pmaStg.xcscheme",
        "pma/ios/pma.xcodeproj/xcshareddata/xcschemes/pmr.xcscheme",
        "pma/ios/pma.xcodeproj/xcshareddata/xcschemes/pmrDev.xcscheme",
        "pma/ios/pma.xcodeproj/xcshareddata/xcschemes/pmrStg.xcscheme",
        "pma/ios/pmaDev/pma dev-Info.plist",
        "pma/package.json",
        "pma/src/common/components/SearchRenderList.tsx",
        "pma/src/common/components/VideoPlayer/RTSPPLayer.tsx",
        "pma/yarn.lock"
      ],
      "removed": [

      ]
    }
  ],
  "total_commits_count": 1,
  "push_options": {
  },
  "repository": {
    "name": "PM Apartment",
    "url": "git@gitlab.com:pmhungnt/pm-apartment.git",
    "description": "",
    "homepage": "https://gitlab.com/pmhungnt/pm-apartment",
    "git_http_url": "https://gitlab.com/pmhungnt/pm-apartment.git",
    "git_ssh_url": "git@gitlab.com:pmhungnt/pm-apartment.git",
    "visibility_level": 0
  }
}
`

**Comment by nth-zik** [comment]
Hi, since we upgrade to 13.0.7. It's not work anymore
It's work when I used version 12

**Comment by foxweb** [comment]
@anujecom fixed.

**Comment by WiredTombstone** [comment]
Experiencing the same issue on 13.1.2 with version 2.14 of this integration. Any guidance?
