### ISSUE TITLE
[Discussion] Merging this plugin into the core application

### ISSUE THREAD

**Issue by oliverguenther** [btey/openproject-gitlab-integration#59]
Hey @btey and other users of the plugin! Thanks a lot for your efforts in building, maintaining, and extending the integration.

We've been following this plugin for a while as we wanted to prioritize a Gitlab integration, but other features as well as sponsorings in the past year have been keeping us busy improving other parts of the applications.

Still, we're interested in providing this plugin as part of the community version. I guess the main advantage of this would be to ensure upgrades to OpenProject come with a maintained version of the GitLab integration. You could submit feature requests directly to the core and get CI and review feedback from us other developers.

What is currently preventing this from happening is the complete lack of automated tests. This would be a requirement to seeing this merged back into the core. Without it, and given that currently the OpenProject team is not using GitLab, we would not have confidence to keep it in maintenance whenever anything in the application changes. 

I'm reaching out to get feedback on this whole idea, as we wouldn't want to impact your motivation or efforts on this plugin. We will likely find the time to prioritize the integration and add to the test suite in the coming months.

Cheers
Oliver from OpenProject

**Comment by btey** [comment]
Hi @oliverguenther,

I think it's a great idea. As you say, sometimes it takes a while to adjust the plugin when a new version of Open Project comes out with changes to the API. Keeping it aligned in the core would avoid this, and it seems like the logical move to follow for the benefit of users.

The absence of automated tests is due to the fact that this started a few years ago as a simple internal proof of concept that has been growing more than expected. For my part, adding the plugin to the core of Open Project would be great news.

Greetings,
Ben

**Comment by wielinde** [comment]
Hey @btey and @foxweb, that is really great news. Thank you for your openness to it.

I propose to move this repo into the openproject core `opf/openproject`, ideally maintaining the git history. A plan could be:
- opf forks this repository
- we bring that repository into a folder structure that fits final structure in `opf/openproject`
- temporarily we add the fork as a remote to `opf/openproject` so that we can merge into a new branch
- then we create a PR in `opf/openproject` with that new branch
- then we can do all the modifications, e.g. adding specs etc. that we consider necessary for a release.

Would that work for you?

**Comment by btey** [comment]
Hi @wielinde 

Sounds like a good plan from my side.

Thank you so much!
Ben

**Comment by foxweb** [comment]
Hi everyone! This is really great news.

Users of our OP fork actively use the GitLab module every day. I have been working on its revision and debugging for a long time in 2023, and now we have no issues in our corporation. In its current state, the GitLab module works perfectly for us.

About specs. I looked at the specs for the GitHub module and tried to write them -- in general, they are very similar and I tried to take them as a basis to rewrite them for GitLab. I don't have the resource for that right now. Instead of writing tests, we test the GitLab module immediately on real users 😄 

Further I am ready to contribute to writing tests for this module, I have a lot of experience working with it.

**Comment by oliverguenther** [comment]
With https://github.com/opf/openproject/pull/14881 merged, I assume we can close this issue. The GitLab integration plugin has been migrated and will be shipped with OpenProject 13.4.0. 

@akabiru @btey  It would probably be a good idea to update this repository's README that development continues in the core (and how to contribute perhaps - or linking to our documentation for that), and that current users of the plugin will have to remove the `Gemfile.plugins` entry as part of the update, otherwise they would run into bundler errors due to the same gem being loaded twice.

Apart from that, the update should be smooth for all users as the plugin continues to function as is. All future migrations will be handled by us to ensure ease of updates as well.
