### ISSUE TITLE
500 Error on work package creation

### ISSUE THREAD

**Issue by tamasfe** [btey/openproject-gitlab-integration#8]
Fresh install of OpenProject 12.0.8 with this plugin.

The `https://my-open-project.com/api/v3/projects/my-project/work_packages/form` call fails if this plugin is installed:

```
/app/vendor/bundle/ruby/2.7.0/gems/grape-1.6.0/lib/grape/middleware/base.rb:41:in `rescue in call!': caught error of type ActionController::UrlGenerationError in after callback inside Grape::Middleware::Formatter : No route matches {:action=>"show", :controller=>"work_packages", :id=>nil}, possible unmatched constraints: [:id]
Did you mean?  work_package_url
               work_packages_url
               work_packages_path
               work_package_move_url (StructuredWarnings::StandardWarning)
```

Dockerfile:

```
FROM openproject/community:12

COPY Gemfile.plugins /app/

RUN bundle config unset deployment && bundle install && bundle config set deployment 'true'
RUN ./docker/prod/setup/postinstall.sh
```

Gemfile.plugins:

```rb
group :opf_plugins do
  gem "openproject-gitlab_integration", git: "https://github.com/btey/openproject-gitlab-integration.git", branch: "master"
end
```

I suspect that the plugin accidentally overwrites existing routes, and hopefully should be an easy fix. Unfortunately I don't know enough about ruby nor the code structure to contribute though.

**Comment by btey** [comment]
Hi Ferenc,

I think I don't quite understand what your problem is. Currently I don't get any errors if I try to create a new WP. I attach screenshots with v12.0.8 + Gitlab plugin v2.0.3.

Could you describe exactly all the steps you are doing until you get the error? It is the only way to try to reproduce the problem.

<img width="1573" alt="Screenshot 2022-03-02 at 14 44 33" src="https://user-images.githubusercontent.com/14983519/156441214-654348cc-1db6-40fe-848a-eab0c5a367c6.png">

<img width="1572" alt="Screenshot 2022-03-02 at 14 54 06" src="https://user-images.githubusercontent.com/14983519/156441244-d5a08481-600b-4e30-8b6c-c55e3c5ef167.png">

<img width="1573" alt="Screenshot 2022-03-02 at 14 53 04" src="https://user-images.githubusercontent.com/14983519/156441261-887c2a46-249a-4b3c-a596-f075f65004a8.png">

<img width="1573" alt="Screenshot 2022-03-02 at 14 53 25" src="https://user-images.githubusercontent.com/14983519/156441272-fa2a2670-b43a-4420-a6cb-1505207f4d35.png">

<img width="1573" alt="Screenshot 2022-03-02 at 15 10 43" src="https://user-images.githubusercontent.com/14983519/156441733-82ea752e-83f0-4b48-ae36-c217f5253a52.png">



Thanks!
Ben

**Comment by tamasfe** [comment]
Thanks for the quick response!

I haven't done any extra steps other than what I described:
- Build the image with the given Dockerfile
- Start the instance, log in
- Try to create a work package in any project

I've tried building it based on the `12.0.7` and `dev` image tags as well, but the angular build fails with type errors using those.

I've added a recording that demonstrates the issue, although it doesn't contain too much new info:

https://user-images.githubusercontent.com/25967296/156459771-c78de963-382d-4696-9b1f-d94caef1bc4e.mp4

And the upstream `openproject/community:12` docker image (left) and the modified one (right) running next to each other (the 403 error is due to cookie conflicts because they share the same host):

![2022-03-02_23-19](https://user-images.githubusercontent.com/25967296/156460383-ba7184e3-e776-4f19-bfa3-ba068d7d686b.png)

Tell me there is something else I can provide to help resolving the issue.

**Comment by btey** [comment]
Hi @tamasfe,

I have been doing tests and I have been able to reproduce the error. It seems to happen only using the OpenProject docker image. If you build your own image putting the code in place this error does not occur. As a temporary solution you can follow the steps that @aleuffre made in a PR (only that it is not necessary to modify the OpenProject code base) here.

Hi @oliverguenther, we've seen this issue when using the OpenProject default docker image with the gitlab plugin, where the  links to create WP don't work, and when we use the quick menu (green + tor left) to create a new WP the main page goes blank. But if we build the docker image with all the OpenProject code putting the plugin in place then it works ok. Let me know if you would like to reopen a ticket in OpenProject or create a new one so you can schedule it in your calendar at your convenience.

Thank you all!
Ben

**Comment by oliverguenther** [comment]
Hi @btey , this indeed is a load error issue that is unrelated to this plugin. However, due to it it exposes a bug in the github plugin that was the origin for your representer extension. This code in the core is simply not evaluated.

For the sake of fixing it in your plugin, I opened the mentioned PR.

Best
Oliver
