### ISSUE TITLE
Improve commit message on Gitlab snippets dropdown

### ISSUE THREAD

**Issue by ElantanaFernando** [btey/openproject-gitlab-integration#9]
Hello,

I found that the git snippets dropdown, the commit message does not have the proper `OP` or `PP` set on the issue number:
```
[#40] Commit message

https://openproject.***/work_packages/40
```
However, modifying the file 
[git-actions.service.ts](https://github.com/btey/openproject-gitlab-integration/blob/master/frontend/module/git-actions/git-actions.service.ts)

line 76 from
```ruby
return `[#${id}] ${title}
```
to 
```ruby
return `[OP#${id}] ${title}
```

solves it (altough making all the links open.

Since I am not really good with ruby, someone can make animprovement here to be able to choose between the two commit messages with **OP** or **PP**

**Comment by btey** [comment]
Hi Fernando!

I have kept the original code of the Snippets based on the plugin to integrate Github in OpenProject. And since in this implementation there are two options, perhaps it could be interesting to include a change. In any case, it is not related to Ruby, but to TypeScript since it directly affects the frontend, which is Angular.

I don't know how many people are using this plugin. I add a poll to see what the general preference would be. Feel free to choose an option. Possible options:
- Leave it as it is
- Include OP only
- Include PP only
- Add an additional snippet and include an option in each one: one with OP and one with PP.

/polls "Leave it as it is" "Include OP only" "Include PP only" "Add an additional snippet and include an option in each one: one with OP and one with PP"

**Comment by btey** [comment]
Sorry Fernando, I've been keeping this ticket open all this time hoping to see some numbers, and now it turns out that the voting plugin has stopped working without prior notice from Github... and it hasn't even registered the votes. I don't know since when it stopped working.

In any case, I also do not see that many users have commented on it. For now I will leave it as it is.
